### ISSUE TITLE
Using pimd

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/plugin-multicast#17]
Using pimd to support all mutlicast protocols
https://github.com/troglobit/pimd

**Comment by Vinzent82** [comment]
Hello as I currently can not run home assistant with the RasperryMatic add on (see ticket linked above) I´d like to ask whether this enhancement is far away or something already on the horizon?

**Comment by ElFaro1** [comment]
Hello, is there a time horizon for a solution? I would like to continue with HA.

**Comment by jens-maus** [comment]
Hi @pvizeli. Are there any chances to see pimd support in plugin-multicast soon? It would really help the RaspberryMatic add-on to finally support the HmIPW-DRAP and HmIP-HAP gateway which rely on multicast UDP network traffic and thus cannot be used in combination with the Add-on due to the missing multicast UDP routing (see https://github.com/jens-maus/RaspberryMatic/issues/1373)

**Comment by pvizeli** [comment]
Currently, I don't have any manpower that can work on this. I guess somewhat around Q3 could be realistic

**Comment by jens-maus** [comment]
> Currently, I don't have any manpower that can work on this. I guess somewhat around Q3 could be realistic

Thanks for the info. If you can, however, assist me to some extend I can try to work on `pimd` integration within `plugin_multicast` myself. So if you could quickly summarize what you might think might be required here and how to do that I can indeed try to work on it an prepare a PR. But as said, I would need some assistance on that matter from you, I guess.

**Comment by gamer123** [comment]
@pvizeli is Q3 still realistic ? 
Is there a way to support or assist you ?

**Comment by simabr** [comment]
Just wanted to install the RasperryMatic add on (which is even the offically recommended addon) but can't do so because my setup requires HmIP-HAP to be used as range extenders. Please take you time for the issue.

**Comment by campinge** [comment]
hello @pvizeli, thank you for the work done so far! I just wanted to check in and see if there was any success in finding manpower to solve this problem. I just switched to HA and am amazed by it, but now had to find out that I cannot integrate it with my DRAP.

**Comment by dn-gt** [comment]
Hello, I just identified I cannot reach my Homematic IP Wired DRAP due to this limitation. I would be also curious whether I need to find an alternative to the Raspberrymatic addon or whether we can expect a solution in foreseeable time?

**Comment by katter** [comment]
@pvizeli For helping you with a start. I am running HA OS on an Odroid. In the underlying build root kernel is compiled to *not support* Multicast forwarding though [`# CONFIG_IP_MROUTE is not set`](https://github.com/home-assistant/operating-system/blob/d17a739f485324df077b4cd059b371b6ec2637c2/buildroot-external/board/hardkernel/kernel-amlogic.config#L966) which gives you:
```
net.ipv4.conf.all.mc_forwarding = 0
net.ipv4.conf.default.mc_forwarding = 0
net.ipv4.conf.docker0.mc_forwarding = 0
net.ipv4.conf.dummy0.mc_forwarding = 0
net.ipv4.conf.eth0.mc_forwarding = 0
net.ipv4.conf.hassio.mc_forwarding = 0
net.ipv4.conf.lo.mc_forwarding = 0
``` (and so forth for eth/veth...)
which will result in pimd telling you: `Cannot enable multicast routing in kernel: Protocol not available`

If I have some time I will look at this further. Only issue is, that I do not have a Test-Env here...

**Comment by pvizeli** [comment]
You can make an PR against https://github.com/home-assistant/operating-system/blob/dev/buildroot-external/kernel/hassos.config - then it will be in nightly for testing it. Thanks for help out @katter

**Comment by jens-maus** [comment]
@katter 
> If I have some time I will look at this further. Only issue is, that I do not have a Test-Env here...

First of all, thanks for doing the initial step in looking into this and that you already identified that some changes to HomeAssistantOS are required for `pimd` to work correctly. Please let me know as soon as you feel you have a first working test environment or potentially working pimd setup so that I can see if I could give you a hand regarding pimd integration in plugin-multicast. This is indeed highly appreciated!

**Comment by katter** [comment]
I can now start pimd in the container after installing the apk from alpines edge/testing repo. Now we can start testing the functionality. It's probably more difficult to then later proof that it doesn't mess up something else.

**Comment by gamer123** [comment]
@jens-maus Thanks for working on this feature, have you seen this ?

**Comment by jens-maus** [comment]
@katter
> With last nights dev build of Home Assistant OS I can now start pimd in the home assistant_multicast container after installing the apk from alpines edge/testing repo. Now we can start testing the functionality. It's probably more difficult to then later proof that it doesn't mess up something else.

Did you have any progress on getting `pimd` compiled/integrated in plugin-multicast yet? Would be great if you could quickly document your steps here that you took to get an own plugin-multicast container compiled with pimd included so that I could potentially take over the work and try it myself...

**Comment by Meza100** [comment]
hi @pvizeli / hi @jens-maus 
is there some new news? I tried to integrate one of my HmIP-HAP, but now I saw, that there is the problem with the pimd. It is possible to extend the range with the power plugs 'til the problem is solved? How long could it take until it's solved?

Thanks and kind regards,
Stefan

**Comment by Rainerlan** [comment]
I would very much appreciate a fix, too!
Any idea when this might be fixed?

**Comment by MelleD** [comment]
I have read both tickets completely. What is still unclear to me.
Is there currently any idea to solve the problem or is the solution still completely unclear?

**Comment by Thorsten1982** [comment]
> @MelleD That's the same question I'm asking myself.

**Comment by Thorsten1982** [comment]
@jens-maus    Thanks for the info. You can't quite see through what really needs to be done to make it work. Is there a way to show the developers that there are many users who want an implementation?

**Comment by jens-maus** [comment]
No, you can only wait and see if/when the HA developers are implementing macvlan support for addon containers. Until this happens continue to use my supplied workaround patch (https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant#hmip-haphmipw-drap-support-patch) to get a HmIP-DRAP/HmIP-HAP working with a RaspberryMatic HA add-on container or simply switch to a full fledged RaspberryMatic VM or host system until this functionality has been added by the HA devs.

**Comment by MelleD** [comment]
> No, you can only wait and see if/when the HA developers are implementing macvlan support for addon containers.

Is there a open ticket for this request?

**Comment by jens-maus** [comment]
> > No, you can only wait and see if/when the HA developers are implementing macvlan support for addon containers.
> 
> Is there a open ticket for this request?

No, but I have direct contact to them and they are already working on it more or less...

**Comment by MelleD** [comment]
> No, but I have direct contact to them and they are already working on it more or less...

Otherwise I would have subscribed to it :)

**Comment by hmax-72** [comment]
Hi! Any update on that? I would really appreciate if it would be possible to migrate my RaspberryMatic-Setup to the HA-AddOn but support for HmIP-DRAP is essential for me (therefore also this enhancement).
