### ISSUE TITLE
Erron on Multicast plugin install

### ISSUE THREAD

**Issue by martusi61** [home-assistant/plugin-multicast#2]
I have a tvbox with Armbian (Debian) and Docker, my architectur is aarch64 and machine type is qemuarm-64, after update to HA 0.108.4 and Supervisor 217 in this i received the error:

20-04-16 01:49:29 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'
20-04-16 01:49:29 WARNING (MainThread) [supervisor.plugins.multicast] Error on install Multicast plugin. Retry in 30sec
20-04-16 01:49:59 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json

I tryed many things but no solution, i have my domotic system down!!!

**Comment by pvizeli** [comment]
Crosspost
